apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: 192.168.1.183:443/test/grey:v31
        name: grey-test
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-argo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
  type: NodePort

